"""Build a follow-up question for ambiguous/low-confidence fields.

Task 5. Copy tone per ../../bot-docs/06-agent-workflow.md §6. A flat miss
(zero candidates) uses a static template — there's nothing field-specific
an LLM could add. A genuinely ambiguous field (`CardDraft.ambiguous_candidates`
— 2+ fuzzy candidates survived `settings.fuzzy_match_floor`, from
resolve.py) instead gets a short, specific question generated by one LLM
call per bot-docs/06-agent-workflow.md §Step 7: "the one justified second
LLM call generates a short, specific question from the ambiguity data only
(candidate list + context)".
"""

import logging

from openai import OpenAIError

from src.config import settings
from src.core.exceptions import UpstreamServiceException
from src.integrations.azure_openai_client import call_with_retry, get_client
from src.models.card_draft import CardDraft

logger = logging.getLogger("clarify")

_FIELD_QUESTIONS = {
    "project_id": "Which project should this go under?",
    "board_id": "Which board should this go on?",
    "title": "What should the title be?",
    "assignee": "Who should this be assigned to?",
}

_FIELD_LABELS = {
    "project_id": "project",
    "board_id": "board",
}

_CONFIRMATION_PROMPTS = {
    "assignee": "I matched this to a SimBoard user for the assignee — is that correct? (yes/no)",
    "title": 'Title: "{value}" — is that correct? (yes/no)',
    "project_id": "I matched this to a project with lower confidence — is that correct? (yes/no)",
    "board_id": "I matched this to a board with lower confidence — is that correct? (yes/no)",
}

_CANDIDATE_QUESTION_SYSTEM_PROMPT = """You write one short, specific \
follow-up question for a Teams bot that could not tell which record the \
user meant. You are given a field name and a list of ambiguous candidate \
names. Ask the user which one they meant, naming the candidates. One \
sentence, no preamble, no markdown, no quotes around the whole sentence."""


async def _generate_candidate_question(field: str, candidates: list[str]) -> str:
    """Generate a short "did you mean X or Y?"-style question via an LLM call.

    For one ambiguous field, per bot-docs/06-agent-workflow.md §Step 7.

    Args:
        field: The `CardDraft.unresolved_fields`/`ambiguous_candidates` key
            (e.g. `"project_id"`, `"assignee:Sweta"`).
        candidates: 2+ candidate display names that survived the fuzzy
            match floor (see `pipeline.resolve._match_with_ambiguity`) —
            must be non-empty.

    Returns:
        One short plain-text sentence naming the candidates and asking
        which one the user meant.

    Raises:
        UpstreamServiceException: if the Azure OpenAI call fails, or
            returns an empty response.

    Side effects:
        Makes an outbound LLM API call (network, billable, latency-bound).
    """
    label = _FIELD_LABELS.get(field, "assignee" if field.startswith("assignee:") else field)
    user_content = f"Field: {label}\nCandidates: {', '.join(candidates)}"

    try:
        completion = await call_with_retry(
            lambda: get_client().chat.completions.create(
                model=settings.azure_openai_deployment,
                messages=[
                    {"role": "system", "content": _CANDIDATE_QUESTION_SYSTEM_PROMPT},
                    {"role": "user", "content": user_content},
                ],
                # gpt-5-mini is a reasoning model — hidden reasoning tokens
                # are drawn from this same budget before any visible output
                # is produced, so a tight cap (previously 60) can leave
                # `message.content` empty even on a 200 OK. Generous
                # headroom here since this is a cheap, low-latency call.
                max_completion_tokens=400,
            )
        )
    except OpenAIError as exc:
        raise UpstreamServiceException(
            f"Azure OpenAI clarification-question call failed: {exc}"
        ) from exc

    text = completion.choices[0].message.content
    if not text or not text.strip():
        raise UpstreamServiceException("Azure OpenAI returned an empty clarification question")

    return text.strip()


async def build_clarification_prompt(draft: CardDraft) -> str:
    """Compose the follow-up question to send back to the user.

    Used when a draft has one or more unresolved fields and/or fields
    pending yes/no confirmation. One line per field: an ambiguous
    unresolved field (`draft.ambiguous_candidates`) gets an LLM-generated
    candidate question; a flat-miss unresolved field gets a static
    template; a pending-confirmation field gets a static yes/no template
    (project/board/assignee confirmation questions are generic — the
    draft only carries resolved ids, not display names; see
    `pipeline.resolve.resolve`).

    Args:
        draft: A `CardDraft` where `unresolved_fields` and/or
            `pending_confirmation_fields` is non-empty (as determined by
            `pipeline.confidence.needs_clarification`). Passing a draft
            where both are empty is a caller error — behavior in that
            case is undefined until implemented.

    Returns:
        A single plain-text message asking the user to resolve the
        listed `unresolved_fields` and/or confirm the listed
        `pending_confirmation_fields`.

    Raises:
        UpstreamServiceException: if generating a candidate question for
            an ambiguous field fails (see `_generate_candidate_question`).

    Side effects:
        Makes one outbound LLM API call per ambiguous field in
        `draft.unresolved_fields`.
    """
    lines = ["I need a bit more info before creating this card:"]
    for field in draft.unresolved_fields:
        candidates = draft.ambiguous_candidates.get(field)
        if candidates:
            question = await _generate_candidate_question(field, candidates)
            lines.append(f"- {question}")
        elif field.startswith("assignee:"):
            name = field.split(":", 1)[1]
            lines.append(
                f'- I couldn\'t find a SimBoard user matching "{name}". Who should this be assigned to?'
            )
        else:
            lines.append(f"- {_FIELD_QUESTIONS.get(field, f'Please clarify: {field}')}")

    for field in draft.pending_confirmation_fields:
        prompt = _CONFIRMATION_PROMPTS.get(field, f"Please confirm: {field} (yes/no)")
        lines.append(f"- {prompt.format(value=draft.title)}")

    return "\n".join(lines)
